{
 "title": "PostgreSQL dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "pgloadgen: queries completed",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pgloadgen_nqueries_done[1m])) BY (type, sql)",
     "legendFormat": "{{type}} (\"{{sql}}\")"
    }
   ]
  },
  {
   "title": "pgloadgen: query latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(pgloadgen_query_latency_us[1m])) BY (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(pgloadgen_query_latency_us[1m])) BY (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(pgloadgen_query_latency_us[1m])) BY (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(irate(pgloadgen_query_latency_us_sum[1m]))/sum(irate(pgloadgen_query_latency_us_count[1m]))",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.5, sum(irate(pgloadgen_query_latency_us[1m])) BY (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "pgloadgen: queries outstanding",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pgloadgen_nqueries_started - pgloadgen_nqueries_done",
     "legendFormat": "{{type}} (\"{{sql}}\")"
    }
   ]
  },
  {
   "title": "pgloadgen: queries with errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pgloadgen_nqueries_failed[1m])) BY (type, sql)",
     "legendFormat": "{{type}} (\"{{sql}}\")"
    }
   ]
  },
  {
   "title": "pgloadgen: error messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pgloadgen_error_messages[1m])) BY (errorMessage)",
     "legendFormat": "message: << {{errorMessage}} >>"
    }
   ]
  },
  {
   "title": "postgres: buffer activity",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_alloc[1m]))",
     "legendFormat": "buffer allocations"
    },
    {
     "expr": "sum(irate(stat_bgwriter_buffers_checkpoint[1m]))",
     "legendFormat": "buffer writes by checkpointer"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_backend[1m]))  ",
     "legendFormat": "buffer writes by backends"
    },
    {
     "expr": "sum(irate(pg_stat_bgwriter_buffers_clean[1m]))  ",
     "legendFormat": "buffer writes by bgwriter"
    }
   ]
  },
  {
   "title": "postgres: connections, by state",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_activity_connections) BY (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "postgres: tuple count, \"test_table\" relation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_n_live_tup{relname=\"test_table\"}",
     "legendFormat": "live tuples"
    },
    {
     "expr": "pg_stat_user_tables_n_dead_tup{relname=\"test_table\"}",
     "legendFormat": "dead tuples"
    },
    {}
   ]
  },
  {
   "title": "postgres: vacuum activity, \"test_table\" relation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_user_tables_autovacuum_count{relname=\"test_table\"}",
     "legendFormat": "autovacuums completed"
    },
    {
     "expr": "pg_stat_user_tables_vacuum_count{relname=\"test_table\"}",
     "legendFormat": "vacuums completed"
    },
    {
     "expr": "pg_stat_user_tables_autovacuum_count{relname=\"test_table\"}",
     "legendFormat": "autoanalyzes completed"
    },
    {
     "expr": "pg_stat_user_tables_autovacuum_count{relname=\"test_table\"}",
     "legendFormat": "analyzes completed"
    }
   ]
  }
 ]
}